# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sVEUmf8IYuMFdidQ55YaWS8KWy4Tn1xx
"""

import json
# import os
# path = "/content/drive/My Drive"
# product_json=[]
# with open(path+'/netaporter_gb.json') as fp:
#     for product in fp.readlines():
#         product_json.append(json.loads(product))
        
import pandas as pd
data=pd.read_json("https://greendeck-datasets-2.s3.amazonaws.com/netaporter_gb_similar.json",lines=True,orient='columns')
id1=[]
for i in data.index:
  #print(data['_id'][i].type)
  d=data['_id'][i]
  data['_id'][i]=d['$oid']
  #print(i)
  #id1+=[id]

data.head()

id1=[]
id2=[]
id3=[]
for i in data.index:
  d=data['price'][i]
  id1+=[d['offer_price']['value']]
  id2+=[d['regular_price']['value']]
  id3+=[d['basket_price']['value']]
data.insert(9,"offer_price",id1)
data.insert(9,"regular_price",id2)
data.insert(9,"basket_price",id3)

df=data[['_id','regular_price','offer_price','basket_price']]
id=[]
for i in data.index:
  id+=[df['regular_price'][i]-df['offer_price'][i]]
df.insert(4,'Discounted_price',id)

t=[]
for i in data.index:
  d=data['brand'][i]
  t+=[d['name']]
df.insert(1,'brand_name',t)


df1=df.groupby(['brand_name']).mean()

id=[]
for i in data.index:
  id+=[data['similar_products'][i]['website_results']]
df.insert(2,'similar_products',id)

id=[]
for i in data.index:
  t=[]
  d=df['similar_products'][i]
  if d['5da94f4e6d97010001f81d72']['meta']['total_results']==1:
    if d['5da94f4e6d97010001f81d72']['meta']['min_price']['basket']<df['basket_price'][i]:
      t+=['5da94f4e6d97010001f81d72']
  
  if d['5da94f270ffeca000172b12e']['meta']['total_results']==1:
    if d['5da94f270ffeca000172b12e']['meta']['min_price']['basket']<df['basket_price'][i]:
      t+=['5da94f270ffeca000172b12e']
  if d['5d0cc7b68a66a100014acdb0']['meta']['total_results']==1:
    if d['5d0cc7b68a66a100014acdb0']['meta']['min_price']['basket']<df['basket_price'][i]:
      t+=['5d0cc7b68a66a100014acdb0']
  if d['5da94ef80ffeca000172b12c']['meta']['total_results']==1:
    if d['5da94ef80ffeca000172b12c']['meta']['min_price']['basket']<df['basket_price'][i]:
      t+=['5da94ef80ffeca000172b12c']
  if d['5da94e940ffeca000172b12a']['meta']['total_results']==1:
    if d['5da94e940ffeca000172b12a']['meta']['min_price']['basket']<df['basket_price'][i]:
      t+=['5da94e940ffeca000172b12a']
  id+=[t]
  
df.insert(2,'expensive_list',id)

id=[]
for i in data.index:
  t=[]
  d=df['similar_products'][i]
  if d['5da94f4e6d97010001f81d72']['meta']['total_results']==1:
    if d['5da94f4e6d97010001f81d72']['meta']['min_price']['basket']<df['basket_price'][i]:
      t+=[d['5da94f4e6d97010001f81d72']['meta']['min_price']['basket']]
  
  if d['5da94f270ffeca000172b12e']['meta']['total_results']==1:
    if d['5da94f270ffeca000172b12e']['meta']['min_price']['basket']<df['basket_price'][i]:
      t+=[d['5da94f270ffeca000172b12e']['meta']['min_price']['basket']]
  if d['5d0cc7b68a66a100014acdb0']['meta']['total_results']==1:
    if d['5d0cc7b68a66a100014acdb0']['meta']['min_price']['basket']<df['basket_price'][i]:
      t+=[d['5d0cc7b68a66a100014acdb0']['meta']['min_price']['basket']]
  if d['5da94ef80ffeca000172b12c']['meta']['total_results']==1:
    if d['5da94ef80ffeca000172b12c']['meta']['min_price']['basket']<df['basket_price'][i]:
      t+=[d['5da94ef80ffeca000172b12c']['meta']['min_price']['basket']]
  if d['5da94e940ffeca000172b12a']['meta']['total_results']==1:
    if d['5da94e940ffeca000172b12a']['meta']['min_price']['basket']<df['basket_price'][i]:
      t+=[d['5da94e940ffeca000172b12a']['meta']['min_price']['basket']]
  id+=[t]
  
df.insert(2,'sim_basket_price',id)

del df['similar_products']

df.expensive_list = df.expensive_list.apply(lambda x: [0] if len(x)==0 else x)
df.sim_basket_price = df.sim_basket_price.apply(lambda x: [0] if len(x)==0 else x)

series=pd.DataFrame(df['expensive_list'].tolist(),index=df.index).stack()
s2=pd.DataFrame(df['sim_basket_price'].tolist(),index=df.index).stack()


series.index=series.index.droplevel(1)
s2.index=s2.index.droplevel(1)

df=pd.concat([df,series,s2], axis=1)
df.reset_index(inplace=True)
df.drop('index', inplace=True , axis=1)


df=df.rename(columns = {0:'expensive_id',1:'comp_basket_price'})

id=[]
for i in df.index:
  if df['comp_basket_price'][i]!=0:
    id+=[(-df['comp_basket_price'][i]+df['basket_price'][i])/df['comp_basket_price'][i]]
  else:
    id+=[0]
df.insert(8,'fluctuation',id)

df['fluctuation']=df['fluctuation']*100

